name: first workflow
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Run on Ubuntu
        run: date
  job2:
    runs-on: windows-latest
    steps:
      - name: Run on Windows
        run: date
  job3:
     runs-on: macos-latest
     steps:
      - name: Run on macos
        run: date
  job4:
     needs: [job1, job2, job3]
     runs-on: ubuntu-latest
     steps:
       - name: Run on ubuntu
         run: date
